server:
  port: 9091

spring:
  application:
    name: implicit-resource-server

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: clientapp
      client-secret: 112233
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      # token有效性检查
      token-info-uri: http://127.0.0.1:9090/oauth/check_token
      resourceId-id: oauth2-resource
    # 授权地址
    authorize-uri: http://127.0.0.1:9090/oauth/authorize
    # 授权后重定向地址
    redirect_uri: http://127.0.0.1:9091/login/callback