server:
  port: 9091

spring:
  application:
    name: password-resource-server

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: clientapp
      client-secret: 112233
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      token-info-uri: http://127.0.0.1:9090/oauth/check_token # 获得 Token 信息的 URL
      resourceId-id: oauth2-resource
    # 自定义的获取访问令牌URL
    access-token-uri: http://127.0.0.1:9090/oauth/token