server:
  port: 9091

spring:
  application:
    name: authorization-code-resource-server

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: clientapp
      client-secret: 112233
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      token-info-uri: http://127.0.0.1:9090/oauth/check_token # 获得 Token 信息的 URL
      resourceId-id: oauth2-resource
    # 获取访问令牌URL
    access-token-uri: http://127.0.0.1:9090/oauth/token
    # 授权地址
    authorize-uri: http://127.0.0.1:9090/oauth/authorize
    # 授权后重定向地址
    redirect_uri: http://127.0.0.1:9091/oauth2_token/callback