server:
  port: 9090

spring:
  application:
    name: client-credentials-authorization-server

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: clientapp
      client-secret: 112233